"""
templates.py — Render the HTML digest email.
"""

from collections import defaultdict
from datetime import datetime


def render_email(
    articles: list[dict],
    cfg: dict,
    intro: str = "",
    action_items: list[dict] | None = None,
) -> str:
    now = datetime.now().strftime("%A, %d %B %Y — %H:%M")
    count = len(articles)

    # Group articles by category, preserving insertion order.
    by_category: dict[str, list[dict]] = defaultdict(list)
    for a in articles:
        by_category[a.get("category", "Uncategorized")].append(a)

    sections = ""
    for category, items in by_category.items():
        sections += f"""
        <tr><td style="padding:24px 8px 8px;">
          <h2 style="margin:0;font-size:15px;font-weight:700;color:#1e3a5f;
                      text-transform:uppercase;letter-spacing:.06em;
                      border-bottom:2px solid #1e3a5f;padding-bottom:8px;">
            {_esc(category)} ({len(items)})
          </h2>
        </td></tr>
        <tr><td style="padding:0 8px 16px;">"""

        for a in items:
            pub = ""
            if a.get("published"):
                try:
                    pub = datetime.fromtimestamp(a["published"] / 1000).strftime(
                        "%d %b %Y"
                    )
                except (TypeError, ValueError, OSError):
                    pass

            reason_html = ""
            if a.get("reason"):
                reason_html = f"""
              <div style="background:#eff6ff;border-left:3px solid #3b82f6;
                          padding:8px 12px;margin-bottom:10px;border-radius:0 4px 4px 0;">
                <span style="font-size:11px;font-weight:600;color:#1d4ed8;
                             text-transform:uppercase;letter-spacing:.04em;">Why this matters</span>
                <p style="margin:4px 0 0;font-size:13px;line-height:1.5;color:#1e40af;">
                  {_esc(a['reason'])}
                </p>
              </div>"""

            sections += f"""
          <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;
                      padding:20px 24px;margin-bottom:16px;">
            <div style="font-size:11px;color:#6b7280;text-transform:uppercase;
                        letter-spacing:.05em;margin-bottom:6px;">
              {_esc(a['source'])} {f'&middot; {pub}' if pub else ''}
            </div>
            <h3 style="margin:0 0 10px;font-size:17px;font-weight:600;line-height:1.35;">
              <a href="{_esc(a['url'])}" style="color:#1d4ed8;text-decoration:none;">
                {_esc(a['title'])}
              </a>
            </h3>{reason_html}
            <p style="margin:0;font-size:14px;line-height:1.65;color:#374151;">
              {_esc(a['summary'])}
            </p>
            <a href="{_esc(a['url'])}"
               style="display:inline-block;margin-top:12px;font-size:13px;
                      color:#2563eb;text-decoration:none;">
              Read full article &rarr;
            </a>
          </div>"""

        sections += """
        </td></tr>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Feed Digest</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,
             'Segoe UI',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
    <tr><td align="center" style="padding:32px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" role="presentation"
             style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr><td style="background:#1e3a5f;border-radius:8px 8px 0 0;
                        padding:28px 32px;">
          <h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:700;">
            Feed Digest
          </h1>
          <p style="margin:6px 0 0;font-size:13px;color:#93c5fd;">{now}</p>
          <p style="margin:6px 0 0;font-size:13px;color:#93c5fd;">
            {count} article{'s' if count != 1 else ''} across {len(by_category)} categories
          </p>
        </td></tr>

        <!-- Intro -->
        {f'''<tr><td style="background:#ffffff;padding:20px 32px;">
          <p style="margin:0;font-size:15px;line-height:1.6;color:#374151;font-style:italic;">
            {_esc(intro)}
          </p>
        </td></tr>''' if intro else ''}

        {_render_action_items(action_items)}

        <!-- Category sections -->
        {sections}

        {_render_fell_through(action_items)}

        <!-- Footer -->
        <tr><td style="background:#e5e7eb;border-radius:0 0 8px 8px;
                        padding:16px 32px;text-align:center;">
          <p style="margin:0;font-size:12px;color:#6b7280;">
            Generated by feed-digest &middot; powered by Claude
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>"""


def _render_action_items(action_items: list[dict] | None) -> str:
    if not action_items:
        return ""

    items_html = ""
    for item in action_items:
        action_text = _esc(item["action"])
        source_html = ""
        if item.get("source_url") and item.get("source_title"):
            source_html = (
                f' <a href="{_esc(item["source_url"])}" '
                f'style="color:#2563eb;text-decoration:none;font-size:12px;">'
                f'({_esc(item["source_title"])})</a>'
            )
        items_html += f"""
              <li style="margin-bottom:8px;font-size:14px;line-height:1.5;color:#1f2937;">
                {action_text}{source_html}
              </li>"""

    return f"""<tr><td style="padding:16px 32px 8px;">
          <div style="background:#fef3c7;border:1px solid #f59e0b;border-radius:8px;
                      padding:20px 24px;">
            <h2 style="margin:0 0 12px;font-size:15px;font-weight:700;color:#92400e;
                        text-transform:uppercase;letter-spacing:.06em;">
              Action Items
            </h2>
            <ul style="margin:0;padding-left:20px;">{items_html}
            </ul>
          </div>
        </td></tr>"""


def _render_fell_through(action_items: list[dict] | None) -> str:
    if not action_items:
        return ""

    fell_through = [
        item for item in action_items
        if item.get("source_url") and item.get("source_title")
    ]
    if not fell_through:
        return ""

    links_html = ""
    for item in fell_through:
        links_html += f"""
              <li style="margin-bottom:6px;font-size:13px;line-height:1.5;">
                <a href="{_esc(item["source_url"])}"
                   style="color:#2563eb;text-decoration:none;">
                  {_esc(item["source_title"])}
                </a>
              </li>"""

    return f"""<tr><td style="padding:8px 32px 16px;">
          <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;
                      padding:16px 24px;">
            <h2 style="margin:0 0 10px;font-size:14px;font-weight:700;color:#6b7280;
                        text-transform:uppercase;letter-spacing:.06em;">
              Fell Through the Cracks
            </h2>
            <p style="margin:0 0 8px;font-size:12px;color:#9ca3af;">
              Articles referenced in today&rsquo;s action items that didn&rsquo;t make the main digest:
            </p>
            <ul style="margin:0;padding-left:20px;">{links_html}
            </ul>
          </div>
        </td></tr>"""


def _esc(s: str) -> str:
    return (
        (s or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
